export const SignUpLoginPageLocators = {
  nameInput: 'signup-name',
  emailInput: 'signup-email',
  signUpButton: 'signup-button',
  passwordInput: 'password',
  firstNameInput: 'first_name',
  lastNameInput: 'last_name',
  addressInput: 'address',
  countryDropdown: 'country',
  countryOption: (country: string) => `option[value="${country}"]`,
  stateInput: 'state',
  cityInput: 'city',
  zipCodeInput: 'zipcode',
  mobileNumberInput: 'mobile_number',
  createAccountButton: 'create-account',
  continueButton: 'continue-button',
  loginEmailInput: 'login-email',
  loginPasswordInput: 'login-password',
  loginButton: 'login-button',
} as const;
